"""Build config/language_geo.yml: for each of our languages, the countries where it is official or the
majority language (ADR 0023). The globe colours countries BY LANGUAGE: we see languages, not countries.

Starting point: Wikidata P37 (official language) of every current country with an ISO 3166-1 alpha-3 code
(P298), mapped to our language codes through ``official_languages`` in config/analytics.yml. Then a hand
check (ADD / REMOVE below), so regenerating gives the same file.

    python -m lookedup.language_geo            # writes config/language_geo.yml and app/data/language_geo.json
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict

import yaml

from lookedup.analytics.config import load
from lookedup.dumps import session
from lookedup.settings import CONFIG_DIR, ROOT

log = logging.getLogger(__name__)

GEO_FILE = CONFIG_DIR / "language_geo.yml"
APP_GEO_FILE = ROOT / "app" / "data" / "language_geo.json"

SPARQL = """
SELECT ?iso3 ?num ?name ?lang WHERE {
  VALUES ?type { wd:Q6256 wd:Q3624078 wd:Q15634554 wd:Q779415 }  # country, sovereign state, state with limited
  ?c wdt:P31 ?type; wdt:P298 ?iso3; wdt:P37 ?lang.                 # recognition, special administrative region
  OPTIONAL { ?c wdt:P299 ?num }
  FILTER NOT EXISTS { ?c wdt:P576 ?dissolved }
  ?c rdfs:label ?name. FILTER(lang(?name) = "en")
}"""

# Hand check (2026-10-09) of the raw P37 lists. Each entry says why.
ADD = {
    "en": ["USA"],         # English is the national language (P37 missing)
    "zh": ["CHN", "TWN"],  # P37 points to Chinese varieties outside our mapping
    "es": ["URY", "PRI"],  # Uruguay (P37 missing), Puerto Rico (territory, Spanish majority)
    "fa": ["AFG"],         # Dari is Persian; fawiki serves it
    "ru": ["KGZ"],         # official language (P37 missing)
    "sr": ["MNE"],         # plurality language of Montenegro
}
REMOVE = {
    "ja": ["PLW"],         # official only in one state of Palau (Angaur)
    "es": ["USA", "ATG"],  # not official, not the majority language
    "ar": ["AFG", "ERI"],  # not official (AFG) / working language only (ERI)
}


# Anchor country per language: where the app draws the language's point for spread arcs. The most
# populous country among the language's countries; single-country languages use their only country.
ANCHOR = {"en": "USA", "es": "MEX", "pt": "BRA", "fr": "FRA", "ar": "EGY", "zh": "CHN", "ru": "RUS", "de": "DEU",
          "it": "ITA", "nl": "NLD", "sv": "SWE", "sr": "SRB", "el": "GRC", "ro": "ROU", "tr": "TUR", "ko": "KOR",
          "fa": "IRN"}


def fetch() -> list[dict]:
    r = session().get("https://query.wikidata.org/sparql", params={"query": SPARQL, "format": "json"}, timeout=120)
    r.raise_for_status()
    return [{k: v["value"] for k, v in b.items()} for b in r.json()["results"]["bindings"]]


def build(rows: list[dict], languages: list[str]) -> tuple[dict, dict]:
    """(by_language {code: [iso3...]}, countries {iso3: {name, num}})."""
    cfg = load()
    to_code = {f"http://www.wikidata.org/entity/{q}": c for q, c in cfg.raw["official_languages"].items()}
    by_lang: dict[str, set[str]] = defaultdict(set)
    countries: dict[str, dict] = {}
    for r in rows:
        iso3 = r["iso3"].upper()
        countries.setdefault(iso3, {"name": r["name"], "num": r.get("num")})
        if r.get("num") and not countries[iso3]["num"]:
            countries[iso3]["num"] = r["num"]
        code = to_code.get(r["lang"])
        if code in languages:
            by_lang[code].add(iso3)
    for code, isos in ADD.items():
        by_lang[code] |= set(isos)
    for code, isos in REMOVE.items():
        by_lang[code] -= set(isos)
    missing = {"TWN": ("Taiwan", "158"), "PRI": ("Puerto Rico", "630"), "CHN": ("China", "156")}
    for iso3, (name, num) in missing.items():
        countries.setdefault(iso3, {"name": name, "num": num})
    out = {code: sorted(by_lang.get(code, set())) for code in languages}
    used = {i for isos in out.values() for i in isos}
    return out, {i: countries[i] for i in sorted(used) if i in countries}


def write(by_lang: dict, countries: dict) -> None:
    header = ("# Languages -> countries where the language is official or the majority language (ADR 0023).\n"
              "# Generated by `python -m lookedup.language_geo` from Wikidata P37, then hand-checked (ADD/REMOVE in\n"
              "# lookedup/language_geo.py). The globe colours countries by the attention IN A LANGUAGE: we see\n"
              "# languages, not countries. A country listed under several languages takes the max.\n")
    anchors = {code: ANCHOR.get(code, isos[0] if isos else None) for code, isos in by_lang.items()}
    body = {"languages": by_lang, "anchors": anchors,
            "countries": {i: {"name": c["name"], "iso_numeric": c["num"]} for i, c in countries.items()}}
    GEO_FILE.write_text(header + yaml.safe_dump(body, allow_unicode=True, sort_keys=False, width=120))
    # the app keys countries by ISO numeric (world-atlas ids); Kosovo has none and keeps its alpha-3
    app = {code: sorted({countries[i]["num"] or i for i in isos if i in countries}) for code, isos in by_lang.items()}
    APP_GEO_FILE.parent.mkdir(parents=True, exist_ok=True)
    num = lambda i: countries[i]["num"] or i
    APP_GEO_FILE.write_text(json.dumps({"schema_version": 1, "languages": app,
                                        "anchors": {c: num(a) for c, a in anchors.items() if a in countries}},
                                       separators=(",", ":")))


def main() -> None:
    from lookedup.languages import active_codes

    logging.basicConfig(level=logging.INFO)
    by_lang, countries = build(fetch(), active_codes())
    write(by_lang, countries)
    for code, isos in by_lang.items():
        log.info("%s: %d countries", code, len(isos))


if __name__ == "__main__":
    main()
